-- execute this before Liquibase

CREATE SCHEMA IF NOT EXISTS sample AUTHORIZATION "sample";
SET search_path = sample;
GRANT ALL ON ALL TABLES IN SCHEMA sample TO "sample";
ALTER DEFAULT PRIVILEGES IN SCHEMA sample GRANT ALL ON TABLES TO "sample";
GRANT SELECT ON ALL TABLES IN SCHEMA sample TO "sample";
ALTER DEFAULT PRIVILEGES IN SCHEMA sample GRANT SELECT ON TABLES TO "sample";
